version: "3.8"

services:
  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  node-app:
    build:
      context: ./node-server
    ports:
      - "5050:5050"
    networks:
      - app-network

  python-app:
    build:
      context: ./python-server
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - react-app
      - node-app
      - python-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
